aliases:
  - &configurations-for-xcode
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: make bootstrap
      - run: xcodebuild -workspace SourceKitten.xcworkspace -scheme sourcekitten build-for-testing|xcpretty -r junit
      - store_test_results:
          path: build/reports/
      - run: xcodebuild -workspace SourceKitten.xcworkspace -scheme sourcekitten $XCODE_FLAGS_FOR_TEST test-without-building
      - run: echo "ruby-2.4" > ~/.ruby-version
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path vendor/bundle || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
      - run: bundle exec pod lib lint

  - &steps-for-swiftpm
    - checkout
    - run: git submodule update --init --recursive
    - run: swift test
    - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install https://raw.github.com/Homebrew/homebrew-core/master/Formula/swiftlint.rb && swiftlint lint --strict

  - &steps-for-linux
    - checkout
    - run: swift test

version: 2
jobs:

  xcode_10:
    environment:
      XCODE_FLAGS_FOR_TEST: -parallel-testing-enabled NO
    macos:
      xcode: "10.1.0"
    <<: *configurations-for-xcode

  swiftpm_4.2:
    macos:
      xcode: "10.1.0"
    steps: *steps-for-swiftpm

  # linux jobs
  linux_swift_4.2:
    docker:
      - image: norionomura/swift:42
    steps: *steps-for-linux

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_10
      - swiftpm_4.2
      - linux_swift_4.2
