included:
 - Cerise
 - CeriseTests

excluded:
 - Pods

whitelist_rules:
 - array_init
 - attributes
 - block_based_kvo
 - class_delegate_protocol
 - closing_brace
 - closure_end_indentation
 - closure_spacing
 - colon
 - comma
 - compiler_protocol_init
 - conditional_returns_on_newline
 - contains_over_first_not_nil
 - control_statement
 - custom_rules
 - cyclomatic_complexity
 - discarded_notification_center_observer
 - discouraged_direct_init
 - dynamic_inline
 - empty_count
 - empty_enum_arguments
 - empty_parameters
 - empty_parentheses_with_trailing_closure
 - explicit_init
 - fallthrough
 - first_where
 - for_where
 - generic_type_name
 - implicit_getter
 - implicitly_unwrapped_optional
 - is_disjoint
 - large_tuple
 - leading_whitespace
 - legacy_cggeometry_functions
 - legacy_constant
 - legacy_constructor
 - legacy_nsgeometry_functions
 - line_length
 - mark
 - multiline_parameters
 - multiple_closures_with_trailing_closure
 - number_separator
 - opening_brace
 - operator_usage_whitespace
 - pattern_matching_keywords
 - private_over_fileprivate
 - private_unit_test
 - protocol_property_accessors_order
 - redundant_discardable_let
 - redundant_nil_coalescing
 - redundant_optional_initialization
 - redundant_string_enum_value
 - redundant_void_return
 - return_arrow_whitespace
 - shorthand_operator
 - sorted_first_last
 - statement_position
 - superfluous_disable_command
 - switch_case_alignment
 - switch_case_on_newline
 - syntactic_sugar
 - trailing_comma
 - trailing_newline
 - trailing_semicolon
 - trailing_whitespace
 - type_name
 - unneeded_break_in_switch
 - unneeded_parentheses_in_closure_argument
 - unused_closure_parameter
 - unused_enumerated
 - unused_optional_binding
 - valid_ibinspectable
 - vertical_parameter_alignment
 - vertical_parameter_alignment_on_call
 - vertical_whitespace
 - void_return
 - weak_delegate
 - xctfail_message
 - yoda_condition

cyclomatic_complexity:
 warning: 20
 ignores_case_statements: true

identifier_name:
 min_length: 1
 max_length: 60

large_tuple: 3

line_length: 200

attributes:
  always_on_line_above:
    - "@objc"
    - "@nonobjc"
    - "@available"
    - "@discardableResult"
  always_on_same_line:
    - "@IBOutlet"
    - "@IBAction"
    - "@NSManaged"
    - "@testable"

trailing_comma:
 mandatory_comma: true

type_name:
 min_length: 3
 max_length: 60

type_body_length:
 - 300 # warning
 - 400 # error
