env:
  global:
    - FRAMEWORK_NAME=SwiftyTextTable

script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681
matrix:
  include:
    - script: set -o pipefail && xcodebuild -scheme SwiftyTextTable -project SwiftyTextTable.xcodeproj clean build test | xcpretty
      env: JOB=Xcode9
      os: osx
      osx_image: xcode9
      language: objective-c
      before_install:
        - ./scripts/upstall-carthage.sh
        - ./scripts/upstall-swiftlint.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      before_deploy:
        - carthage build --no-skip-current
        - carthage archive $FRAMEWORK_NAME
    - script:
        - TOOLCHAINS=swift swift build
        - TOOLCHAINS=swift swift test
      env: JOB=SPM
      os: osx
      osx_image: xcode9
      language: objective-c
    - script:
        - swift build
        - swift test
      env: JOB=Linux SWIFT_VERSION=4.0
      sudo: required
      dist: trusty
      language: generic
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  #allow_failures:
  #  - env: JOB=Linux SWIFT_VERSION=4.0

  exclude:
    - script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681

deploy:
  provider: releases
  api_key:
    secure: CLgRTCkr9FXlDS9bTejaSCUN78lT110kyFXsod+LAGZo/zqzebVwo/XTqSIdHV6raWP+KsazUNyt4YhjZgaLG2CCf+MZVY2yelnuE419/rgSqW2FrVkcMqhIc+vFAp57qK/E8mC5GnZO35uhxZ0CM98h75G7pL2ebWu/WmB9zV3nujNl1mTXRIMD9SRihjzM+RjyrNAPZyqvVkFM4nJBUTA3jW+QsbqcNy7ds1Erz/kFsuBHCTbbYaqq+W7vZAL7NQlaqfpcN1jSxh0PuaEjLicCMqzDpkd0ODeu1F0r9Ql/9Nf7QiWv8BusBdwBqee2p+ET7h2hXYXzkNYkVCz1Gp8twviXcQNyfM3h8lhqcvsYPcjXIWEHzwgNsUlltFH62//JqlJegU17p2WniJXtHNHsjcEnjC1ngLix+IBSv9z1uJPYGisSA4AwLjiiEQc8UhRNT8DOmrVmRcODIU8PMfJPiwmA8eBpVb6bwD/zwMDtH3E40gO1qTIvz496I0VT+81GfDYv0xfHcER++OBpCNjLnnInTFCDmF8XaPR14jusCyWbAeL5pGb4K6HcwYPWM5g27/2yaUNY7haI1BFi/p/apQ9sFzWeHJ0BG3hwNUPrLwIsqTyXZm5Q/OuDeaHa7Ye9qbJtO281m09a2qWEmBx/fZHQuT4eNbe1W/xoWcA=
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: scottrhoyt/SwiftyTextTable
    tags: true
    condition: $JOB = Xcode9
